/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExceptionBase: typeof import('./../src/components/custom/ExceptionBase.vue')['default']
    MenuItem: typeof import('./../src/components/common/menuItem.vue')['default']
    Navbar: typeof import('./../src/components/common/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/custom/SvgIcon.vue')['default']
    Tabbar: typeof import('./../src/components/common/Tabbar.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCircle: typeof import('vant/es')['Circle']
    VanIcon: typeof import('vant/es')['Icon']
    VanSpace: typeof import('vant/es')['Space']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
